version: '2'
services:
 db:
   image: mongo
   ports:
     - "27017:27017"
 web:
   build: .
   command: python src/server.py
   volumes:
     - .:/project
   environment:
     - DB_NAME=joy_of_painting
   ports:
     - "8080:8080"
   depends_on:
     - db