version: '2'
services:
 db:
   image: mongo
   ports:
     - "27017:27017"
 app:
   build: .
   command: python src/server.py
   volumes:
     - .:/project
   environment:
     - DB_NAME=joy_of_painting
     - DB_HOST=db
   ports:
     - "8080:8080"
   depends_on:
     - db